from typing import Protocol, Sequence, Optional
from app.domain.models import Campaign

class CampaignRepo(Protocol):
    async def create(self, user_id: int, title: str, description: str = "") -> Campaign: ...
    async def list(self, user_id: int) -> Sequence[Campaign]: ...
    async def get(self, user_id: int, campaign_id: int) -> Optional[Campaign]: ...
    async def set_current(self, user_id: int, campaign_id: int) -> None: ...
    async def get_current(self, user_id: int) -> Optional[Campaign]: ...